### ISSUE TITLE
Report multiple alleles per assembly?

### ISSUE THREAD

**Issue by bananabenana** [tomdstanton/GetAlleles#1]
Very cool tool here. A feature request is functionality that allows multiple hits per genome to be reported.

## Test data
To this genome [INF018_Glu_pos.fasta.txt](https://github.com/tomdstanton/GetAlleles/files/15478833/INF018_Glu_pos.fasta.txt), I added a gene (16S rRNA) [16S_ribosomal_RNA.ffn.txt](https://github.com/tomdstanton/GetAlleles/files/15478832/16S_ribosomal_RNA.ffn.txt)
 to the ends of contig_1 and contig_2 [INF018_Glu_pos_added_16S.fasta.txt](https://github.com/tomdstanton/GetAlleles/files/15478834/INF018_Glu_pos_added_16S.fasta.txt)

## Current functionality
Running GetAlleles returns a single hit for INF018_Glu_pos_added_16S, when in reality, I would expect 3 total hits (as I added the 16S gene in two additional locations. Notably, the hit is at contig_1.

## Proposed feature attempt
Modifying [line]( https://github.com/tomdstanton/GetAlleles/blob/96ddaef843e850c92b738c1de544bbfb9ecdc96e/get_alleles.py#L123C1-L124C1
) to `best_n = 10` but this still returned only a single value.

Thanks!

**Comment by tomdstanton** [comment]
This is due to [this line](https://github.com/tomdstanton/GetAlleles/blob/bfee5ac9a6599b283fd440298a186e15fc72f9ea/get_alleles.py#L327) where the `next()` function will only return the first alignment if there is one.

**Comment by tomdstanton** [comment]
@bananabenana I've made a [patch](https://github.com/tomdstanton/GetAlleles/tree/tomdstanton-patch-1) that addresses this (see #3). I will merge it into master if it works for you 😄
